### ISSUE TITLE
Compiler issue when installing trottersuzuki

### ISSUE THREAD

**Issue by jbduanan** [trotter-suzuki-mpi/trotter-suzuki-mpi#115]
Hi.

I am using Enthought Canopy with Python 3 (64-bit) on a Windows 10 machine.

I tried installing trottersuzuki using pip:
`pip install trottersuzuki`

But I am encountering a compiler problem, so the package does not install completely:
`AttributeError: MSVCCompiler instance has no attribute 'compiler_so'`

The cmd instance can be seen below:
`(Canopy 64bit) C:\Users\Levine Duanan\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Enthought Canopy (64-bit)>pip install trottersuzuki
Collecting trottersuzuki
  Using cached trottersuzuki-1.5.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): numpy in c:\users\levine duanan\appdata\local\enthought\canopy\user\lib\site-packages (from trottersuzuki)
Installing collected packages: trottersuzuki
  Running setup.py install for trottersuzuki ... error
    Complete output from command "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\User\python.exe" -u -c "import setuptools, tokenize;__file__='c:\\users\\levine~1\\appdata\\local\\temp\\pip-build-edq8m9\\trottersuzuki\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\levine~1\appdata\local\temp\pip-8c2xbb-record\install-record.txt --single-version-externally-managed --compile --install-headers "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\User\include\site\python2.7\trottersuzuki":
    Proceeding without CUDA
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\trottersuzuki
    copying trottersuzuki\classes_extension.py -> build\lib.win-amd64-2.7\trottersuzuki
    copying trottersuzuki\tools.py -> build\lib.win-amd64-2.7\trottersuzuki
    copying trottersuzuki\trottersuzuki.py -> build\lib.win-amd64-2.7\trottersuzuki
    copying trottersuzuki\__init__.py -> build\lib.win-amd64-2.7\trottersuzuki
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\levine~1\appdata\local\temp\pip-build-edq8m9\trottersuzuki\setup.py", line 162, in <module>
        cmdclass=cmdclass
      File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.6.2.3262.win-x86_64\lib\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.6.2.3262.win-x86_64\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.6.2.3262.win-x86_64\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\User\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.6.2.3262.win-x86_64\lib\distutils\command\install.py", line 563, in run
        self.run_command('build')
      File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.6.2.3262.win-x86_64\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.6.2.3262.win-x86_64\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.6.2.3262.win-x86_64\lib\distutils\command\build.py", line 127, in run
        self.run_command(cmd_name)
      File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.6.2.3262.win-x86_64\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.6.2.3262.win-x86_64\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\User\lib\site-packages\setuptools\command\build_ext.py", line 49, in run
        _build_ext.run(self)
      File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.6.2.3262.win-x86_64\lib\distutils\command\build_ext.py", line 337, in run
        self.build_extensions()
      File "c:\users\levine~1\appdata\local\temp\pip-build-edq8m9\trottersuzuki\setup.py", line 83, in build_extensions
        customize_compiler_for_nvcc(self.compiler)
      File "c:\users\levine~1\appdata\local\temp\pip-build-edq8m9\trottersuzuki\setup.py", line 65, in customize_compiler_for_nvcc
        default_compiler_so = self.compiler_so
    AttributeError: MSVCCompiler instance has no attribute 'compiler_so'`

I do not know how to go about this problem and any help will be appreciated. Thank you.

**Comment by peterwittek** [comment]
Thanks for the bug report. The difficulty here is that neither of us developers has access to a Windows computer, nor we have the relevant development experience. Nevertheless, we understand that many scientists still use this OS, so we are keen on fixing this bug. I would like to ask for your patience in tracking this one down.

The problem is in ``setup.py``. I made a first attempt to fix it. To test it, please do the following:

1. [Download](https://pypi.python.org/packages/source/t/trottersuzuki/trottersuzuki-1.5.1.tar.gz) the source distribution from PyPI.
2. After you extract it, please overwrite ``setup.py`` with my new version from [here](https://raw.githubusercontent.com/peterwittek/trotter-suzuki-mpi/master/src/Python/setup.py).
3. Run the manual installation: ``python setup.py install``.

If we are lucky, this should do the trick. If not, please report back with the new error message.

**Comment by jbduanan** [comment]
Hi. Thank you for this. I've followed the instructions, but unfortunately, a new error message resulted. Please see below:

`(Canopy 64bit) C:\Users\Levine Duanan\Documents\trottersuzuki-1.5.1>python setup.py install
Proceeding without CUDA
running install
running bdist_egg
running egg_info
writing requirements to trottersuzuki.egg-info\requires.txt
writing trottersuzuki.egg-info\PKG-INFO
writing top-level names to trottersuzuki.egg-info\top_level.txt
writing dependency_links to trottersuzuki.egg-info\dependency_links.txt
reading manifest file 'trottersuzuki.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'trottersuzuki.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
building '_trottersuzuki' extension
Traceback (most recent call last):
  File "setup.py", line 167, in <module>
    cmdclass=cmdclass
  File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.6.2.3262.win-x86_64\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.6.2.3262.win-x86_64\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.6.2.3262.win-x86_64\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\User\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\User\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.6.2.3262.win-x86_64\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.6.2.3262.win-x86_64\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\User\lib\site-packages\setuptools\command\bdist_egg.py", line 161, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\User\lib\site-packages\setuptools\command\bdist_egg.py", line 147, in call_command
    self.run_command(cmdname)
  File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.6.2.3262.win-x86_64\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.6.2.3262.win-x86_64\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\User\lib\site-packages\setuptools\command\install_lib.py", line 10, in run
    self.build()
  File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.6.2.3262.win-x86_64\lib\distutils\command\install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.6.2.3262.win-x86_64\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.6.2.3262.win-x86_64\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\User\lib\site-packages\setuptools\command\build_ext.py", line 49, in run
    _build_ext.run(self)
  File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.6.2.3262.win-x86_64\lib\distutils\command\build_ext.py", line 337, in run
    self.build_extensions()
  File "setup.py", line 87, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.6.2.3262.win-x86_64\lib\distutils\command\build_ext.py", line 446, in build_extensions
    self.build_extension(ext)
  File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\User\lib\site-packages\setuptools\command\build_ext.py", line 174, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.6.2.3262.win-x86_64\lib\distutils\command\build_ext.py", line 496, in build_extension
    depends=ext.depends)
  File "C:\Users\Levine Duanan\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.6.2.3262.win-x86_64\lib\distutils\msvc9compiler.py", line 546, in compile
    extra_postargs)
TypeError: can only concatenate list (not "dict") to list`

Thank you.

**Comment by peterwittek** [comment]
Commit 7240377dc7c2954d28a324d0bae563c777cc33c8 should solve Windows problems. Please try it as follows: start with the source distribution from PyPI. Then copy ``setup.py``, ``cpublock.cpp``, and ``trottersuzuki.h`` from the latest git to the matching directories.
