### ISSUE TITLE
When installing with pip I get numpy not found error even though it is installed.

### ISSUE THREAD

**Issue by vanangamudi** [trotter-suzuki-mpi/trotter-suzuki-mpi#172]
When installing with pip I get numpy not found error even though it is installed local to the venv and also globally. So I compiled the trottersuzuki locally but not sure how to make it accessible to python. 

`````````
pip install trottersuzuki
Collecting trottersuzuki
  Using cached trottersuzuki-1.6.2.tar.gz (218 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/home/vanangamudi/pyenv/activegp/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/vanangamudi/pyenv/activegp/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/vanangamudi/pyenv/activegp/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-ydzlwasd/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-ydzlwasd/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-ydzlwasd/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-ydzlwasd/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.


(activegp) vanangamudi@karunthulai:~/code/saama/Active_Learning_GP/trotter-suzuki-mpi
$ python
Python 3.8.0 (default, Dec  9 2021, 17:53:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.zeros([10,10])
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
>>> 
```

**Comment by phdru** [comment]
Copied from https://stackoverflow.com/a/78982063/7976758 :

`trottersuzuki` doesn't provide binary wheels, only [sdist](https://pypi.org/project/trottersuzuki/#files). When installing from a source distribution modern `pip` first build a wheel in a new isolated virtual environment. In this isolated venv there is no `numpy`. For `pip` to install `numpy` during build phase there must be a file `pyproject.toml` in the package that lists `numpy` as a build dependency. But [there is no](https://github.com/trotter-suzuki-mpi/trotter-suzuki-mpi/tree/master/src/Python) such file. This is a bug in the package.

Until the bug is fixed there is workaround: disable build isolation:
```sh
$ pip install numpy setuptools
$ pip install --no-build-isolation trottersuzuki
```
